---
driver:
  name: vagrant

provisioner:
  name: chef_solo

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.6.0

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[eja_dicom]
    attributes:
