---
driver:
  name: vagrant

provisioner:
  name: chef_solo

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.6.0

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04
  - name: centos-7

suites:
  - name: default
    run_list:
      - recipe[eja_dicom]
    attributes:
      eja_dicom:
        aet: dicombliss
        user: _dicom
        group: _dicom
        output_directory: /opt/dicom_storage
        output_directory_mode: 02775
